on:
  workflow_dispatch:
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - run: |
          haxelib install electron
          ./update.sh
          if [[ $? == 0 ]]; then
            git add -A
            git commit -m "Upgrade to electron $latest"
            git tag $latest
            git config user.name github-actions
            git config user.email github-actions@github.com
            git push
            git push --tags
          fi
