on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - run: |
          ./update.sh
          if [[ $? != 0 ]]; then
            git add -A
            git commit -m "Upgrade to electron $latest"
            git tag $latest
            git config user.name github-actions
            git config user.email github-actions@github.com
            git push
            git push --tags
          fi
